export const items = {
  websites: [
    {
      id: 0,
      title: "StoreMe",
      desc: "Governmental Project that currently ongoing.",
      image: "/portfolio.png",
      link: "",
      type: "Next",
    },
    {
      id: 1,
      title: "MegaWhale",
      desc: "This is web application of Warehouse Management System for DFS Group.",
      image: "/portfolio4.png",
      link: "",
      type: "React",
    },
    {
      id: 2,
      title: "echoMe",
      desc: "This is web application of Warehouse Management System for DFS Group.",
      image: "/portfolio3.png",
      link: "",
      type: "React",
    },
    {
      id: 3,
      title: "InterLogger v3",
      desc: "The purpose of this toy project is to enhance the features of InternetLogger. You can check details of first version of InternetLogger in my project list.",
      image: "/portfolio1.png",
      link: "https://www.notion.so/hohuns17/InternetLogger-3-Web-454d48eeb61b4c0e8b04fe49e325d0b1?pvs=4",
      type: "React",
    },
    {
      id: 4,
      title: "Travel Logger",
      desc: "This project is to make travel logger with by using tour schedule function and mappin to aid visualization as well as details.",
      image: "/portfolio8.png",
      link: "https://www.notion.so/hohuns17/Travel-Logger-364a35a32d1143c18ee566604d064095?pvs=4",
      type: "React",
    },
    {
      id: 5,
      title: "Hans Tour",
      desc: "This project is implemented with pure Sass in order to practice various CSS animations, applications and finally for usage of Sass.",
      image: "/portfolio2.png",
      link: "https://hohuns17.notion.site/Hans-Tours-Travel-agency-website-b94817d554d340de9f5bd4a1e5b4c9a1",
      type: "React",
    },
    {
      id: 6,
      title: "Hans Template v3",
      desc: "Personal template based on MUI5, React Router Dom6, Redux Tool kit, React Data Grid and integrated with Keycloak.",
      image: "/portfolio9.png",
      link: "https://hohuns17.notion.site/HANS-TEMPLATE-1618be2f46734adbad1468e130b6950b",
      type: "React",
    },
    {
      id: 7,
      title: "See More Projects..",
      desc: "There are bunch of projects to explore to..",
      image: "/portfolio7.png",
      link: "https://www.notion.so/hohuns17/d0f4974c1ab64db09ac2d6f5604eaaa6?v=c9bbc5159f04434d8d03e27d92afffb1&pvs=4",
      type: "",
    },
  ],
  applications: [
    {
      id: 0,
      title: "EchoMe Mobile",
      desc: "This is androind mobile application of Warehouse Management System for DFS.",
      image: "/portfolio3.png",
      link: "",
      type: "React",
    },
    {
      id: 1,
      title: "Interlogger Mobile",
      desc: "The purpose of this toy project is to rebuild interlogger v3 web to mobile version. You can check first version from projects list.",
      image: "/portfolio10.png",
      link: "https://www.notion.so/hohuns17/InterLogger-mobile-6774e795f3ab4cdfb0eaceb84c86c255?pvs=4",
      type: "React",
    },
    {
      id: 2,
      title: "Live Weather",
      desc: "Weather apps these days are having too many advertisements and too much information. However, this application will deliver you more accurate weather information that you want with an intuitive and simple UI.",
      image: "/portfolio6.png",
      link: "https://hohuns17.notion.site/Android-Application-Live-Weather-59de78ae7dc3485cbe1f935a625267a9",
      type: "Java",
    },
    {
      id: 3,
      title: "Meals-React",
      desc: "This app introduces various categories of meals depends on cooking time, difficulty, complexity etc. and user even can add it to bookmark and watches it on their favorite sections.",
      image: "/portfolio11.png",
      link: "https://hohuns17.notion.site/Meal-App-570459832d95479481423eaf77bcad79",
      type: "React",
    },
    {
      id: 4,
      title: "Secret exercise of Antiaging",
      desc: "The purpose of this project is to use advanced deep learning technology to develop a facial muscle exercise game to minimize the aging of the human face.",
      image: "/portfolio5.png",
      link: "https://hohuns17.notion.site/Android-Application-Final-Year-Project-Secret-exercise-of-Anti-aging-7c52fe5b77634fd08c649d4c4c57eedd",
      type: "React",
    },
    {
      id: 7,
      title: "See More Projects..",
      desc: "There are bunch of projects to explore to..",
      image: "/portfolio7.png",
      link: "https://www.notion.so/hohuns17/d0f4974c1ab64db09ac2d6f5604eaaa6?v=c9bbc5159f04434d8d03e27d92afffb1&pvs=4",
    },
  ],
};
